import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="bg-white pb-6 sm:pb-8 lg:pb-12">
          <section className="mx-auto max-w-screen-2xl px-4 md:px-8 h-full">
            {children}
          </section >
        </div >
      </body>
    </html>
  )
}
