import './globals.css'
import type { Metadata } from 'next'
import Header from './components/header'

export const metadata: Metadata = {
  title: 'MSC Bellissima Cruise Tour',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className="font-notoj">
        <Header />
        <div className="bg-white pb-6 sm:pb-8 lg:pb-12">
          <section className="mx-auto max-w-(--breakpoint-2xl) h-full">
            {children}
          </section >
        </div >
      </body>
    </html>
  )
}
